/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToe;

import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author xavis
 */
public class tablero5x5 extends javax.swing.JFrame {
    private Tablero tablero;
    
    
    private JLabel[] posicion = new JLabel[25];
    private int[][] matriz = {
        {1, 2, 3, 4, 5},  // Filas
        {6, 7, 8, 9, 10},
        {11, 12, 13, 14, 15},
        {16, 17, 18, 19, 20},
        {21, 22, 23, 24, 25},
        {1, 6, 11, 16, 21},  // Columnas
        {2, 7, 12, 17, 22},
        {3, 8, 13, 18, 23},
        {4, 9, 14, 19, 24},
        {5, 10, 15, 20, 25},
        {1, 7, 13, 19, 25}, // Diagonales
        {5, 9, 13, 17, 21},  
    };
    
    public tablero5x5(String nombre1, String nombre2, JRadioButton rbt3x3, JRadioButton rbt4x4, JRadioButton rbt5x5) {
        initComponents();
        jugador1.setText(nombre1);
        jugador2.setText(nombre2);
        
        this.setLocationRelativeTo(null);
        posicion[0] = pos1;
        posicion[1] = pos2;
        posicion[2] = pos3;
        posicion[3] = pos4;
        posicion[4] = pos5;
        posicion[5] = pos6;
        posicion[6] = pos7;
        posicion[7] = pos8;
        posicion[8] = pos9;
        posicion[9] = pos10;
        posicion[10] = pos11;
        posicion[11] = pos12;
        posicion[12] = pos13;
        posicion[13] = pos14;
        posicion[14] = pos15;
        posicion[15] = pos16;
        posicion[16] = pos17;
        posicion[17] = pos18;
        posicion[18] = pos19;
        posicion[19] = pos20;
        posicion[20] = pos21;
        posicion[21] = pos22;
        posicion[22] = pos23;
        posicion[23] = pos24;
        posicion[24] = pos25;
        
        
        tablero = new Tablero(posicion, matriz, txtTurno, puntoX, puntoO, true, rbt3x3, rbt4x4, rbt5x5);
    }
    
    public tablero5x5() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pos1 = new javax.swing.JLabel();
        pos2 = new javax.swing.JLabel();
        pos3 = new javax.swing.JLabel();
        pos4 = new javax.swing.JLabel();
        pos5 = new javax.swing.JLabel();
        pos6 = new javax.swing.JLabel();
        pos7 = new javax.swing.JLabel();
        pos8 = new javax.swing.JLabel();
        pos9 = new javax.swing.JLabel();
        pos10 = new javax.swing.JLabel();
        pos11 = new javax.swing.JLabel();
        pos12 = new javax.swing.JLabel();
        pos13 = new javax.swing.JLabel();
        pos14 = new javax.swing.JLabel();
        pos15 = new javax.swing.JLabel();
        pos16 = new javax.swing.JLabel();
        pos17 = new javax.swing.JLabel();
        pos18 = new javax.swing.JLabel();
        pos19 = new javax.swing.JLabel();
        pos20 = new javax.swing.JLabel();
        pos21 = new javax.swing.JLabel();
        pos22 = new javax.swing.JLabel();
        pos23 = new javax.swing.JLabel();
        pos24 = new javax.swing.JLabel();
        pos25 = new javax.swing.JLabel();
        jugador1 = new javax.swing.JLabel();
        puntoX = new javax.swing.JLabel();
        txtTurno = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        fichaO = new javax.swing.JLabel();
        fichaX = new javax.swing.JLabel();
        puntoO = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tipoTablero = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(255, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pos1.setBackground(new java.awt.Color(255, 255, 255));
        pos1.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos1.setForeground(new java.awt.Color(255, 255, 255));
        pos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos1MousePressed(evt);
            }
        });
        jPanel5.add(pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 70));

        pos2.setBackground(new java.awt.Color(255, 255, 255));
        pos2.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos2.setForeground(new java.awt.Color(255, 255, 255));
        pos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos2MousePressed(evt);
            }
        });
        jPanel5.add(pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, 70));

        pos3.setBackground(new java.awt.Color(255, 255, 255));
        pos3.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos3.setForeground(new java.awt.Color(255, 255, 255));
        pos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos3MousePressed(evt);
            }
        });
        jPanel5.add(pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, 70));

        pos4.setBackground(new java.awt.Color(255, 255, 255));
        pos4.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos4.setForeground(new java.awt.Color(255, 255, 255));
        pos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos4MousePressed(evt);
            }
        });
        jPanel5.add(pos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 70, 70));

        pos5.setBackground(new java.awt.Color(255, 255, 255));
        pos5.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos5.setForeground(new java.awt.Color(255, 255, 255));
        pos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos5MousePressed(evt);
            }
        });
        jPanel5.add(pos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 70, 70));

        pos6.setBackground(new java.awt.Color(255, 255, 255));
        pos6.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos6.setForeground(new java.awt.Color(255, 255, 255));
        pos6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos6MousePressed(evt);
            }
        });
        jPanel5.add(pos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, 70));

        pos7.setBackground(new java.awt.Color(255, 255, 255));
        pos7.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos7.setForeground(new java.awt.Color(255, 255, 255));
        pos7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos7MousePressed(evt);
            }
        });
        jPanel5.add(pos7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 70, 70));

        pos8.setBackground(new java.awt.Color(255, 255, 255));
        pos8.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos8.setForeground(new java.awt.Color(255, 255, 255));
        pos8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos8MousePressed(evt);
            }
        });
        jPanel5.add(pos8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 70, 70));

        pos9.setBackground(new java.awt.Color(255, 255, 255));
        pos9.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos9.setForeground(new java.awt.Color(255, 255, 255));
        pos9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos9MousePressed(evt);
            }
        });
        jPanel5.add(pos9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 70, 70));

        pos10.setBackground(new java.awt.Color(255, 255, 255));
        pos10.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos10.setForeground(new java.awt.Color(255, 255, 255));
        pos10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos10MousePressed(evt);
            }
        });
        jPanel5.add(pos10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 70, 70));

        pos11.setBackground(new java.awt.Color(255, 255, 255));
        pos11.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos11.setForeground(new java.awt.Color(255, 255, 255));
        pos11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos11MousePressed(evt);
            }
        });
        jPanel5.add(pos11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, 70));

        pos12.setBackground(new java.awt.Color(255, 255, 255));
        pos12.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos12.setForeground(new java.awt.Color(255, 255, 255));
        pos12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos12MousePressed(evt);
            }
        });
        jPanel5.add(pos12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 70, 70));

        pos13.setBackground(new java.awt.Color(255, 255, 255));
        pos13.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos13.setForeground(new java.awt.Color(255, 255, 255));
        pos13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos13MousePressed(evt);
            }
        });
        jPanel5.add(pos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, 70));

        pos14.setBackground(new java.awt.Color(255, 255, 255));
        pos14.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos14.setForeground(new java.awt.Color(255, 255, 255));
        pos14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos14MousePressed(evt);
            }
        });
        jPanel5.add(pos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 70, 70));

        pos15.setBackground(new java.awt.Color(255, 255, 255));
        pos15.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos15.setForeground(new java.awt.Color(255, 255, 255));
        pos15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos15MousePressed(evt);
            }
        });
        jPanel5.add(pos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, 70));

        pos16.setBackground(new java.awt.Color(255, 255, 255));
        pos16.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos16.setForeground(new java.awt.Color(255, 255, 255));
        pos16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos16MousePressed(evt);
            }
        });
        jPanel5.add(pos16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, 70));

        pos17.setBackground(new java.awt.Color(255, 255, 255));
        pos17.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos17.setForeground(new java.awt.Color(255, 255, 255));
        pos17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos17MousePressed(evt);
            }
        });
        jPanel5.add(pos17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 70, 70));

        pos18.setBackground(new java.awt.Color(255, 255, 255));
        pos18.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos18.setForeground(new java.awt.Color(255, 255, 255));
        pos18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos18MousePressed(evt);
            }
        });
        jPanel5.add(pos18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 70, 70));

        pos19.setBackground(new java.awt.Color(255, 255, 255));
        pos19.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos19.setForeground(new java.awt.Color(255, 255, 255));
        pos19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos19MousePressed(evt);
            }
        });
        jPanel5.add(pos19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 70, 70));

        pos20.setBackground(new java.awt.Color(255, 255, 255));
        pos20.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos20.setForeground(new java.awt.Color(255, 255, 255));
        pos20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos20MousePressed(evt);
            }
        });
        jPanel5.add(pos20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 70, 70));

        pos21.setBackground(new java.awt.Color(255, 255, 255));
        pos21.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos21.setForeground(new java.awt.Color(255, 255, 255));
        pos21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos21MousePressed(evt);
            }
        });
        jPanel5.add(pos21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 70, 70));

        pos22.setBackground(new java.awt.Color(255, 255, 255));
        pos22.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos22.setForeground(new java.awt.Color(255, 255, 255));
        pos22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos22MousePressed(evt);
            }
        });
        jPanel5.add(pos22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 70, 70));

        pos23.setBackground(new java.awt.Color(255, 255, 255));
        pos23.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos23.setForeground(new java.awt.Color(255, 255, 255));
        pos23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos23MousePressed(evt);
            }
        });
        jPanel5.add(pos23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 70, 70));

        pos24.setBackground(new java.awt.Color(255, 255, 255));
        pos24.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos24.setForeground(new java.awt.Color(255, 255, 255));
        pos24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos24MousePressed(evt);
            }
        });
        jPanel5.add(pos24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 70, 70));

        pos25.setBackground(new java.awt.Color(255, 255, 255));
        pos25.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos25.setForeground(new java.awt.Color(255, 255, 255));
        pos25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos25MousePressed(evt);
            }
        });
        jPanel5.add(pos25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 70, 70));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 470, 560));

        jugador1.setFont(new java.awt.Font("Sitka Heading", 2, 24)); // NOI18N
        jugador1.setForeground(new java.awt.Color(255, 255, 255));
        jugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugador1.setText("Jugador 1");
        jPanel4.add(jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 240, 30));

        puntoX.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        puntoX.setForeground(new java.awt.Color(51, 153, 255));
        puntoX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntoX.setText("0");
        jPanel4.add(puntoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 80, 30));

        txtTurno.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        txtTurno.setForeground(new java.awt.Color(255, 204, 0));
        txtTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTurno.setText("Turno de  X");
        jPanel4.add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 240, -1));

        jugador2.setFont(new java.awt.Font("Sitka Heading", 2, 24)); // NOI18N
        jugador2.setForeground(new java.awt.Color(255, 255, 255));
        jugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugador2.setText("Jugador 2");
        jPanel4.add(jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 240, 30));

        fichaO.setFont(new java.awt.Font("Sitka Heading", 2, 20)); // NOI18N
        fichaO.setForeground(new java.awt.Color(255, 51, 51));
        fichaO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaO.setText("O");
        jPanel4.add(fichaO, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 240, 30));

        fichaX.setFont(new java.awt.Font("Sitka Heading", 2, 20)); // NOI18N
        fichaX.setForeground(new java.awt.Color(102, 153, 255));
        fichaX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaX.setText("X");
        jPanel4.add(fichaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 240, 30));

        puntoO.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        puntoO.setForeground(new java.awt.Color(255, 0, 51));
        puntoO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntoO.setText("0");
        jPanel4.add(puntoO, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 80, 30));

        jButton2.setFont(new java.awt.Font("Sitka Banner", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 211, 157));
        jButton2.setText("REGRESAR");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 320, 60));

        jButton1.setFont(new java.awt.Font("Sitka Banner", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 211, 157));
        jButton1.setText("REINICIAR JUEGO");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 320, 90));

        tipoTablero.setFont(new java.awt.Font("Sitka Small", 3, 14)); // NOI18N
        tipoTablero.setForeground(new java.awt.Color(255, 255, 255));
        tipoTablero.setText("3x3");
        jPanel4.add(tipoTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 40, 30));

        mesa.setBackground(new java.awt.Color(102, 51, 0));
        mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/imagenes/bg5x5mesa.png"))); // NOI18N
        mesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/imagenes/bg5x5.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos1MousePressed
        // TODO add your handling code here:
        tablero.ficha(1);
    }//GEN-LAST:event_pos1MousePressed

    private void pos2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos2MousePressed
        // TODO add your handling code here:
        tablero.ficha(2);
    }//GEN-LAST:event_pos2MousePressed

    private void pos3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos3MousePressed
        // TODO add your handling code here:
        tablero.ficha(3);
    }//GEN-LAST:event_pos3MousePressed

    private void pos4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos4MousePressed
        // TODO add your handling code here:
        tablero.ficha(4);
    }//GEN-LAST:event_pos4MousePressed

    private void pos5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos5MousePressed
        // TODO add your handling code here:
        tablero.ficha(5);
    }//GEN-LAST:event_pos5MousePressed

    private void pos6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos6MousePressed
        // TODO add your handling code here:
        tablero.ficha(6);
    }//GEN-LAST:event_pos6MousePressed

    private void pos7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos7MousePressed
        // TODO add your handling code here:
        tablero.ficha(7);
    }//GEN-LAST:event_pos7MousePressed

    private void pos8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos8MousePressed
        // TODO add your handling code here:
        tablero.ficha(8);
    }//GEN-LAST:event_pos8MousePressed

    private void pos9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos9MousePressed
        // TODO add your handling code here:
        tablero.ficha(9);
    }//GEN-LAST:event_pos9MousePressed

    private void pos10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos10MousePressed
        // TODO add your handling code here:
        tablero.ficha(10);
    }//GEN-LAST:event_pos10MousePressed

    private void pos11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos11MousePressed
        // TODO add your handling code here:
        tablero.ficha(11);
    }//GEN-LAST:event_pos11MousePressed

    private void pos12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos12MousePressed
        // TODO add your handling code here:
        tablero.ficha(12);
    }//GEN-LAST:event_pos12MousePressed

    private void pos13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos13MousePressed
        // TODO add your handling code here:
        tablero.ficha(13);
    }//GEN-LAST:event_pos13MousePressed

    private void pos14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos14MousePressed
        // TODO add your handling code here:
        tablero.ficha(14);
    }//GEN-LAST:event_pos14MousePressed

    private void pos15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos15MousePressed
        // TODO add your handling code here:
        tablero.ficha(15);
    }//GEN-LAST:event_pos15MousePressed

    private void pos16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos16MousePressed
        // TODO add your handling code here:
        tablero.ficha(16);
    }//GEN-LAST:event_pos16MousePressed

    private void pos17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos17MousePressed
        // TODO add your handling code here:
        tablero.ficha(17);
    }//GEN-LAST:event_pos17MousePressed

    private void pos18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos18MousePressed
        // TODO add your handling code here:
        tablero.ficha(18);
    }//GEN-LAST:event_pos18MousePressed

    private void pos19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos19MousePressed
        // TODO add your handling code here:
        tablero.ficha(19);
    }//GEN-LAST:event_pos19MousePressed

    private void pos20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos20MousePressed
        // TODO add your handling code here:
        tablero.ficha(20);
    }//GEN-LAST:event_pos20MousePressed

    private void pos21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos21MousePressed
        // TODO add your handling code here:
        tablero.ficha(21);
    }//GEN-LAST:event_pos21MousePressed

    private void pos22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos22MousePressed
        // TODO add your handling code here:
        tablero.ficha(22);
    }//GEN-LAST:event_pos22MousePressed

    private void pos23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos23MousePressed
        // TODO add your handling code here:
        tablero.ficha(23);
    }//GEN-LAST:event_pos23MousePressed

    private void pos24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos24MousePressed
        // TODO add your handling code here:
        tablero.ficha(24);
    }//GEN-LAST:event_pos24MousePressed

    private void pos25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos25MousePressed
        // TODO add your handling code here:
        tablero.ficha(25);
    }//GEN-LAST:event_pos25MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tablero.reinicioJuego();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablero5x5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fichaO;
    private javax.swing.JLabel fichaX;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador2;
    private javax.swing.JLabel mesa;
    private javax.swing.JLabel pos1;
    private javax.swing.JLabel pos10;
    private javax.swing.JLabel pos11;
    private javax.swing.JLabel pos12;
    private javax.swing.JLabel pos13;
    private javax.swing.JLabel pos14;
    private javax.swing.JLabel pos15;
    private javax.swing.JLabel pos16;
    private javax.swing.JLabel pos17;
    private javax.swing.JLabel pos18;
    private javax.swing.JLabel pos19;
    private javax.swing.JLabel pos2;
    private javax.swing.JLabel pos20;
    private javax.swing.JLabel pos21;
    private javax.swing.JLabel pos22;
    private javax.swing.JLabel pos23;
    private javax.swing.JLabel pos24;
    private javax.swing.JLabel pos25;
    private javax.swing.JLabel pos3;
    private javax.swing.JLabel pos4;
    private javax.swing.JLabel pos5;
    private javax.swing.JLabel pos6;
    private javax.swing.JLabel pos7;
    private javax.swing.JLabel pos8;
    private javax.swing.JLabel pos9;
    private javax.swing.JLabel puntoO;
    private javax.swing.JLabel puntoX;
    private javax.swing.JLabel tipoTablero;
    private javax.swing.JLabel txtTurno;
    // End of variables declaration//GEN-END:variables
}
