/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToe;

import java.awt.Color;

/**
 *
 * @author xavis
 */
public class Inicio extends javax.swing.JFrame {
    private Jugador jugador1;
    private Jugador jugador2;


    
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jugador1 = new Jugador("Jugador 1");
        jugador2 = new Jugador("Jugador 2");
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rbt4x4 = new javax.swing.JRadioButton();
        rbt3x3 = new javax.swing.JRadioButton();
        rbt5x5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        nameJugador1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        colorj2 = new javax.swing.JComboBox<>();
        colorj1 = new javax.swing.JComboBox<>();
        nameJugador2 = new javax.swing.JTextField();
        btn_iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        XD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de tableros: ");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        buttonGroup1.add(rbt4x4);
        rbt4x4.setForeground(new java.awt.Color(255, 255, 255));
        rbt4x4.setText("4x4");
        jPanel4.add(rbt4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        buttonGroup1.add(rbt3x3);
        rbt3x3.setForeground(new java.awt.Color(255, 255, 255));
        rbt3x3.setSelected(true);
        rbt3x3.setText("3x3");
        jPanel4.add(rbt3x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        buttonGroup1.add(rbt5x5);
        rbt5x5.setForeground(new java.awt.Color(255, 255, 255));
        rbt5x5.setText("5x5");
        jPanel4.add(rbt5x5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador 1:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 30));

        nameJugador1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameJugador1.setText("Jugador 1");
        nameJugador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameJugador1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJugador1FocusLost(evt);
            }
        });
        jPanel4.add(nameJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Colores");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Colores");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 60, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(":Jugador 2");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 80, 30));

        colorj2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Rojo", "Verde", "Azul", "Amarillo" }));
        jPanel4.add(colorj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 140, -1));

        colorj1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Rojo", "Verde", "Azul", "Amarillo" }));
        jPanel4.add(colorj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 230, 150, -1));

        nameJugador2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameJugador2.setText("Jugador 2");
        nameJugador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameJugador2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJugador2FocusLost(evt);
            }
        });
        nameJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJugador2ActionPerformed(evt);
            }
        });
        jPanel4.add(nameJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 240, 50));

        btn_iniciar.setText("Iniciar juego");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/imagenes/TrickBG.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        XD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XD.setText("Jugador 2");
        XD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                XDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                XDFocusLost(evt);
            }
        });
        XD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XDActionPerformed(evt);
            }
        });
        jPanel4.add(XD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 240, 50));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("XAVI ARCAEA INSIGHT");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
    String nombre1 = nameJugador1.getText();
    String nombre2 = nameJugador2.getText();
    
    if(rbt3x3.isSelected()){
        new tablero3x3(nombre1, nombre2, rbt3x3, rbt4x4, rbt5x5).setVisible(true); 
    }else if(rbt4x4.isSelected()){
        new tablero4x4(nombre1, nombre2, rbt3x3, rbt4x4, rbt5x5).setVisible(true);
    }else if(rbt5x5.isSelected()){
        new tablero5x5(nombre1, nombre2, rbt3x3, rbt4x4, rbt5x5).setVisible(true);
    }
this.dispose();
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void nameJugador1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJugador1FocusGained
        // TODO add your handling code here:
        if(nameJugador1.getText().equals("Jugador 1")){
            nameJugador1.setText("");
        }
    }//GEN-LAST:event_nameJugador1FocusGained

    private void nameJugador1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJugador1FocusLost
        // TODO add your handling code here:
        if(nameJugador1.getText().equals("")){
            nameJugador1.setText("Jugador 1");
        }
    }//GEN-LAST:event_nameJugador1FocusLost

    private void nameJugador2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJugador2FocusGained
        // TODO add your handling code here:
        if(nameJugador2.getText().equals("Jugador 2")){
            nameJugador2.setText("");
        }
    }//GEN-LAST:event_nameJugador2FocusGained

    private void nameJugador2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJugador2FocusLost
        // TODO add your handling code here:
        if(nameJugador2.getText().equals("")){
            nameJugador2.setText("Jugador 2");
        }
    }//GEN-LAST:event_nameJugador2FocusLost

    private void nameJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJugador2ActionPerformed

    private void XDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_XDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_XDFocusGained

    private void XDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_XDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_XDFocusLost

    private void XDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XDActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
    }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField XD;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> colorj1;
    private javax.swing.JComboBox<String> colorj2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nameJugador1;
    private javax.swing.JTextField nameJugador2;
    private javax.swing.JRadioButton rbt3x3;
    private javax.swing.JRadioButton rbt4x4;
    private javax.swing.JRadioButton rbt5x5;
    // End of variables declaration//GEN-END:variables
}
