/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToe;

import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author xavis
 */
public class tablero4x4 extends javax.swing.JFrame {
    private Tablero tablero;
    
    
    private JLabel[] posicion = new JLabel[16];
    private int[][] matriz = {
        {1, 2, 3, 4},  // Filas
        {5, 6, 7, 8},
        {9, 10, 11, 12},
        {13, 14, 15, 16},
        {1, 5, 9, 13},  // Columnas
        {2, 6, 10, 14},
        {3, 7, 11, 15},
        {4, 8, 12, 16},
        {1, 6, 11, 16},  // Diagonales
        {4, 7, 10, 13}
    };
    
    public tablero4x4(String nombre1, String nombre2, JRadioButton rbt3x3, JRadioButton rbt4x4, JRadioButton rbt5x5) {
        initComponents();
        jugador1.setText(nombre1);
        jugador2.setText(nombre2);
        
        this.setLocationRelativeTo(null);
        posicion[0] = pos1;
        posicion[1] = pos2;
        posicion[2] = pos3;
        posicion[3] = pos4;
        posicion[4] = pos5;
        posicion[5] = pos6;
        posicion[6] = pos7;
        posicion[7] = pos8;
        posicion[8] = pos9;
        posicion[9] = pos10;
        posicion[10] = pos11;
        posicion[11] = pos12;
        posicion[12] = pos13;
        posicion[13] = pos14;
        posicion[14] = pos15;
        posicion[15] = pos16;
        
        
        tablero = new Tablero(posicion, matriz, txtTurno, puntoX, puntoO, true, rbt3x3, rbt4x4, rbt5x5);
    }
    
    public tablero4x4() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pos1 = new javax.swing.JLabel();
        pos2 = new javax.swing.JLabel();
        pos3 = new javax.swing.JLabel();
        pos4 = new javax.swing.JLabel();
        pos5 = new javax.swing.JLabel();
        pos6 = new javax.swing.JLabel();
        pos7 = new javax.swing.JLabel();
        pos8 = new javax.swing.JLabel();
        pos9 = new javax.swing.JLabel();
        pos10 = new javax.swing.JLabel();
        pos11 = new javax.swing.JLabel();
        pos12 = new javax.swing.JLabel();
        pos13 = new javax.swing.JLabel();
        pos14 = new javax.swing.JLabel();
        pos15 = new javax.swing.JLabel();
        pos16 = new javax.swing.JLabel();
        jugador1 = new javax.swing.JLabel();
        puntoX = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jugador2 = new javax.swing.JLabel();
        fichaO = new javax.swing.JLabel();
        fichaX = new javax.swing.JLabel();
        puntoO = new javax.swing.JLabel();
        txtTurno = new javax.swing.JLabel();
        txtGanador = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(255, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pos1.setBackground(new java.awt.Color(255, 255, 255));
        pos1.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos1MousePressed(evt);
            }
        });
        jPanel5.add(pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 80, 90));

        pos2.setBackground(new java.awt.Color(255, 255, 255));
        pos2.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos2MousePressed(evt);
            }
        });
        jPanel5.add(pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, 90));

        pos3.setBackground(new java.awt.Color(255, 255, 255));
        pos3.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos3MousePressed(evt);
            }
        });
        jPanel5.add(pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 80, 90));

        pos4.setBackground(new java.awt.Color(255, 255, 255));
        pos4.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos4MousePressed(evt);
            }
        });
        jPanel5.add(pos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 80, 90));

        pos5.setBackground(new java.awt.Color(255, 255, 255));
        pos5.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos5MousePressed(evt);
            }
        });
        jPanel5.add(pos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, 90));

        pos6.setBackground(new java.awt.Color(255, 255, 255));
        pos6.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos6MousePressed(evt);
            }
        });
        jPanel5.add(pos6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 80, 90));

        pos7.setBackground(new java.awt.Color(255, 255, 255));
        pos7.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos7MousePressed(evt);
            }
        });
        jPanel5.add(pos7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 80, 90));

        pos8.setBackground(new java.awt.Color(255, 255, 255));
        pos8.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos8MousePressed(evt);
            }
        });
        jPanel5.add(pos8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 80, 90));

        pos9.setBackground(new java.awt.Color(255, 255, 255));
        pos9.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos9MousePressed(evt);
            }
        });
        jPanel5.add(pos9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 80, 90));

        pos10.setBackground(new java.awt.Color(255, 255, 255));
        pos10.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos10MousePressed(evt);
            }
        });
        jPanel5.add(pos10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 90));

        pos11.setBackground(new java.awt.Color(255, 255, 255));
        pos11.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos11MousePressed(evt);
            }
        });
        jPanel5.add(pos11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 80, 90));

        pos12.setBackground(new java.awt.Color(255, 255, 255));
        pos12.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos12MousePressed(evt);
            }
        });
        jPanel5.add(pos12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 80, 90));

        pos13.setBackground(new java.awt.Color(255, 255, 255));
        pos13.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos13MousePressed(evt);
            }
        });
        jPanel5.add(pos13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 80, 90));

        pos14.setBackground(new java.awt.Color(255, 255, 255));
        pos14.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos14MousePressed(evt);
            }
        });
        jPanel5.add(pos14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 80, 90));

        pos15.setBackground(new java.awt.Color(255, 255, 255));
        pos15.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos15MousePressed(evt);
            }
        });
        jPanel5.add(pos15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 80, 90));

        pos16.setBackground(new java.awt.Color(255, 255, 255));
        pos16.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        pos16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pos16MousePressed(evt);
            }
        });
        jPanel5.add(pos16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 80, 90));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 470, 560));

        jugador1.setFont(new java.awt.Font("Sitka Heading", 2, 20)); // NOI18N
        jugador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jugador1.setText("Jugador 1");
        jPanel4.add(jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 190, 30));

        puntoX.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        puntoX.setForeground(new java.awt.Color(255, 153, 0));
        puntoX.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        puntoX.setText("0");
        jPanel4.add(puntoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 30, 30));

        regresar.setFont(new java.awt.Font("Sitka Banner", 3, 14)); // NOI18N
        regresar.setText("REGRESAR");
        regresar.setBorder(null);
        regresar.setBorderPainted(false);
        regresar.setContentAreaFilled(false);
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel4.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 130, 50));

        jButton1.setFont(new java.awt.Font("Sitka Banner", 3, 14)); // NOI18N
        jButton1.setText("REINICIAR JUEGO");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 190, 50));

        jugador2.setFont(new java.awt.Font("Sitka Heading", 2, 20)); // NOI18N
        jugador2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jugador2.setText("Jugador 2");
        jPanel4.add(jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 230, 30));

        fichaO.setFont(new java.awt.Font("Sitka Heading", 2, 20)); // NOI18N
        fichaO.setForeground(new java.awt.Color(255, 204, 51));
        fichaO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaO.setText("O");
        jPanel4.add(fichaO, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 30, 30));

        fichaX.setFont(new java.awt.Font("Sitka Heading", 2, 20)); // NOI18N
        fichaX.setForeground(new java.awt.Color(255, 153, 51));
        fichaX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaX.setText("X");
        jPanel4.add(fichaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 20, 30));

        puntoO.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        puntoO.setForeground(new java.awt.Color(255, 204, 0));
        puntoO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        puntoO.setText("0");
        jPanel4.add(puntoO, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 30, 30));

        txtTurno.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        txtTurno.setForeground(new java.awt.Color(255, 102, 0));
        txtTurno.setText("Turno de  X");
        jPanel4.add(txtTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        txtGanador.setFont(new java.awt.Font("Sitka Small", 3, 14)); // NOI18N
        txtGanador.setForeground(new java.awt.Color(204, 102, 0));
        txtGanador.setText("4x4");
        jPanel4.add(txtGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 50, 30));

        mesa.setBackground(new java.awt.Color(102, 51, 0));
        mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/imagenes/bg4x4mesa.png"))); // NOI18N
        mesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/imagenes/bg4x4.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos16MousePressed
        // TODO add your handling code here:
        tablero.ficha(16);
    }//GEN-LAST:event_pos16MousePressed

    private void pos15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos15MousePressed
        // TODO add your handling code here:
        tablero.ficha(15);
    }//GEN-LAST:event_pos15MousePressed

    private void pos14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos14MousePressed
        // TODO add your handling code here:
        tablero.ficha(14);
    }//GEN-LAST:event_pos14MousePressed

    private void pos13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos13MousePressed
        // TODO add your handling code here:
        tablero.ficha(13);
    }//GEN-LAST:event_pos13MousePressed

    private void pos12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos12MousePressed
        // TODO add your handling code here:
        tablero.ficha(12);
    }//GEN-LAST:event_pos12MousePressed

    private void pos11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos11MousePressed
        // TODO add your handling code here:
        tablero.ficha(11);
    }//GEN-LAST:event_pos11MousePressed

    private void pos10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos10MousePressed
        // TODO add your handling code here:
        tablero.ficha(10);
    }//GEN-LAST:event_pos10MousePressed

    private void pos9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos9MousePressed
        // TODO add your handling code here:
        tablero.ficha(9);
    }//GEN-LAST:event_pos9MousePressed

    private void pos8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos8MousePressed
        // TODO add your handling code here:
        tablero.ficha(8);
    }//GEN-LAST:event_pos8MousePressed

    private void pos7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos7MousePressed
        // TODO add your handling code here:
        tablero.ficha(7);
    }//GEN-LAST:event_pos7MousePressed

    private void pos6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos6MousePressed
        // TODO add your handling code here:
        tablero.ficha(6);
    }//GEN-LAST:event_pos6MousePressed

    private void pos5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos5MousePressed
        // TODO add your handling code here:
        tablero.ficha(5);
    }//GEN-LAST:event_pos5MousePressed

    private void pos4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos4MousePressed
        // TODO add your handling code here:
        tablero.ficha(4);
    }//GEN-LAST:event_pos4MousePressed

    private void pos3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos3MousePressed
        // TODO add your handling code here:
        tablero.ficha(3);
    }//GEN-LAST:event_pos3MousePressed

    private void pos2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos2MousePressed
        // TODO add your handling code here:
        tablero.ficha(2);
    }//GEN-LAST:event_pos2MousePressed

    private void pos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos1MousePressed
        // TODO add your handling code here:
        tablero.ficha(1);
    }//GEN-LAST:event_pos1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tablero.reinicioJuego();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablero4x4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fichaO;
    private javax.swing.JLabel fichaX;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador2;
    private javax.swing.JLabel mesa;
    private javax.swing.JLabel pos1;
    private javax.swing.JLabel pos10;
    private javax.swing.JLabel pos11;
    private javax.swing.JLabel pos12;
    private javax.swing.JLabel pos13;
    private javax.swing.JLabel pos14;
    private javax.swing.JLabel pos15;
    private javax.swing.JLabel pos16;
    private javax.swing.JLabel pos2;
    private javax.swing.JLabel pos3;
    private javax.swing.JLabel pos4;
    private javax.swing.JLabel pos5;
    private javax.swing.JLabel pos6;
    private javax.swing.JLabel pos7;
    private javax.swing.JLabel pos8;
    private javax.swing.JLabel pos9;
    private javax.swing.JLabel puntoO;
    private javax.swing.JLabel puntoX;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel txtGanador;
    private javax.swing.JLabel txtTurno;
    // End of variables declaration//GEN-END:variables
}
